# Generated by Django 4.2.3 on 2023-07-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='activities',
            field=models.ManyToManyField(to='main_app.activity'),
        ),
    ]
